name: docking
channels:
  - conda-forge
dependencies:
  - python=3.11.15
  - smina=2020.12.10
  - openbabel=3.1.1
  - rdkit=2023.09.6
  - numpy=1.26.4
  - pandas=3.0.5
  - scipy=1.17.1
  - matplotlib=3.10.9
  - biopython=1.88
  - jupyterlab=4.6.3
